CREATE TABLE `Customers` (
	`CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`CUSTOMER_FIRST_NAME` varchar(14) NOT NULL,
	`CUSTOMER_LAST_NAME` varchar(14) NOT NULL,
	`CUSTOMER_USERNAME` varchar(14) NOT NULL AUTO_INCREMENT,
	`CUSTOMER_PASSWORD` varchar(14) NOT NULL AUTO_INCREMENT,
	`CUSTOMER_MOBILE` varchar(14) NOT NULL,
	`CUSTOMER_HOMEPHONE` varchar(14) NOT NULL,
	PRIMARY KEY (`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`)
);

CREATE TABLE `Orders` (
	`RECIPENT_ID` INT NOT NULL,
	`ORDER_ID` INT NOT NULL,
	`SIZE` DECIMAL NOT NULL,
	`WEIGHT` DECIMAL NOT NULL,
	`ORDER_PICKED_UP_BY` INT NOT NULL,
	`ORDER_DROPPED_OFF_BY` INT NOT NULL,
	`DATE_OF_ORDER` DATE NOT NULL,
	`DATE_OF_PICKUP` DATE,
	`DATE_OF_DELIVERY` DATE,
	`COST` DECIMAL NOT NULL,
	`CUSTOMER_ID` INT NOT NULL,
	`DESCRIPTION` TEXT(100),
	`STATUS` VARCHAR(255) NOT NULL,
	`PICKUP_LOCATION` INT NOT NULL,
	`DROP_OFF_LOCATION` INT NOT NULL,
	PRIMARY KEY (`ORDER_ID`)
);

CREATE TABLE `Cost Weight` (
	`SIZE_SCALER` DECIMAL NOT NULL AUTO_INCREMENT,
	`WEIGHT_SCALER` DECIMAL NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`SIZE_SCALER`,`WEIGHT_SCALER`)
);

CREATE TABLE `Employee` (
	`EMPLOYEE_ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`EMPLOYEE_FIRST_NAME` varchar(14) NOT NULL AUTO_INCREMENT,
	`EMPLOYEE_LAST_NAME` varchar(14) NOT NULL AUTO_INCREMENT UNIQUE,
	`EMPLOYEE_USERNAME` varchar(8-16) NOT NULL AUTO_INCREMENT UNIQUE,
	`EMPLOYEE_PASSWORD` varchar(8-16) NOT NULL AUTO_INCREMENT UNIQUE,
	`EMPLOYEE_MOBILE` varchar(10) NOT NULL UNIQUE,
	PRIMARY KEY (`EMPLOYEE_USERNAME`,`EMPLOYEE_PASSWORD`)
);

CREATE TABLE `Status` (
	`STATUS_DESCRIPTION` VARCHAR(255) NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY (`STATUS_DESCRIPTION`)
);

CREATE TABLE `Website Administrators` (
	`EMPLOYEE_ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY (`EMPLOYEE_ID`)
);

CREATE TABLE `Customers Pickup Addresses` (
	`ADDRESS_ID` INT NOT NULL,
	`CUSTOMER_ID` INT NOT NULL,
	PRIMARY KEY (`ADDRESS_ID`,`CUSTOMER_ID`)
);

CREATE TABLE `Addresses` (
	`ADDRESS_ID` INT NOT NULL,
	`ADDRESS_FIRST_LINE` TEXT(50) NOT NULL,
	`ADDRESS_SECOND_LINE` TEXT(50) NOT NULL,
	`ADDRESS_POSTCODE` INT(4) NOT NULL,
	`ADDRESS_SUBURB` TEXT(24) NOT NULL,
	`ADDRESS_STATE` TEXT(24) NOT NULL,
	`ADDRESS_COUNTRY` TEXT(24) NOT NULL,
	PRIMARY KEY (`ADDRESS_ID`)
);

CREATE TABLE `Deliverable Postcodes` (
	`POSTCODE` INT(4) NOT NULL,
	PRIMARY KEY (`POSTCODE`)
);

CREATE TABLE `Recipent` (
	`RECIPENT_ID` INT NOT NULL UNIQUE,
	`RECIPENT_FIRST_NAME` varchar(14) NOT NULL UNIQUE,
	`RECIPENT_LAST_NAME` varchar(14) NOT NULL UNIQUE,
	PRIMARY KEY (`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`)
);

ALTER TABLE `Orders` ADD CONSTRAINT `Orders_fk0` FOREIGN KEY (`RECIPENT_ID`) REFERENCES `Recipent`(`RECIPENT_ID`);

ALTER TABLE `Orders` ADD CONSTRAINT `Orders_fk1` FOREIGN KEY (`ORDER_PICKED_UP_BY`) REFERENCES `Employee`(`EMPLOYEE_ID`);

ALTER TABLE `Orders` ADD CONSTRAINT `Orders_fk2` FOREIGN KEY (`ORDER_DROPPED_OFF_BY`) REFERENCES `Employee`(`EMPLOYEE_ID`);

ALTER TABLE `Orders` ADD CONSTRAINT `Orders_fk3` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `Customers`(`CUSTOMER_ID`);

ALTER TABLE `Orders` ADD CONSTRAINT `Orders_fk4` FOREIGN KEY (`STATUS`) REFERENCES `Status`(`STATUS_DESCRIPTION`);

ALTER TABLE `Orders` ADD CONSTRAINT `Orders_fk5` FOREIGN KEY (`PICKUP_LOCATION`) REFERENCES `Addresses`(`ADDRESS_ID`);

ALTER TABLE `Orders` ADD CONSTRAINT `Orders_fk6` FOREIGN KEY (`DROP_OFF_LOCATION`) REFERENCES `Addresses`(`ADDRESS_ID`);

ALTER TABLE `Website Administrators` ADD CONSTRAINT `Website Administrators_fk0` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `Employee`(`EMPLOYEE_ID`);

ALTER TABLE `Customers Pickup Addresses` ADD CONSTRAINT `Customers Pickup Addresses_fk0` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `Addresses`(`ADDRESS_ID`);

ALTER TABLE `Customers Pickup Addresses` ADD CONSTRAINT `Customers Pickup Addresses_fk1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `Customers`(`CUSTOMER_ID`);

ALTER TABLE `Addresses` ADD CONSTRAINT `Addresses_fk0` FOREIGN KEY (`ADDRESS_POSTCODE`) REFERENCES `Deliverable Postcodes`(`POSTCODE`);
