/*Cost Weight*/
INSERT INTO `Cost Weight` (`SIZE_SCALER`,`WEIGHT_SCALER`) VALUES ('4.0','1.2');

/*Deliverable Postcodes*/
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4000');
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4001');
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4008');
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4106');
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4169');
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4178');
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4029');
INSERT INTO `Deliverable Postcodes`  (`POSTCODE`) VALUES ('4101');

/*Status*/
INSERT INTO `Status` (`STATUS_DESCRIPTION`) VALUES ('AWAITING PICKUP');
INSERT INTO `Status` (`STATUS_DESCRIPTION`) VALUES ('IN TRANSIT FROM PICK UP LOCATION');
INSERT INTO `Status` (`STATUS_DESCRIPTION`) VALUES ('IN WAREHOUSE');
INSERT INTO `Status` (`STATUS_DESCRIPTION`) VALUES ('IN TRANSIT TO DROP OFF LOCATION');
INSERT INTO `Status` (`STATUS_DESCRIPTION`) VALUES ('DROPPED OFF');

/*Customers*/
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('0','Carlin','Connell','Carlin54','password123','0400123132');
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('1','Rick','James','J.Rick32','imrickjamesbitch','0425854286');
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('2','Tyler','Durden','Tyler96','edward_norton','0400654234');
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('3','Edward','Norton','Edward96','tyler_durden','0400234654');
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('4','Simple','Jack','TopGun','trustnoone','0452345612');
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('5','Katy','Perry','Katty-Kat','fireWorks13','0423853296');
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('6','Taylor','Swift','S.Taylor','thisisit','0402349648');
INSERT INTO `Customers` (`CUSTOMER_ID`,`CUSTOMER_FIRST_NAME`,`CUSTOMER_LAST_NAME`,`CUSTOMER_USERNAME`,`CUSTOMER_PASSWORD`,`CUSTOMER_MOBILE`) VALUES ('7','Joe','Rogan','JRE','ERJJREERJ','0402344218');

/*Employee*/
INSERT INTO `Employee` (`EMPLOYEE_ID`,`EMPLOYEE_FIRST_NAME`,`EMPLOYEE_LAST_NAME`,`EMPLOYEE_USERNAME`,`EMPLOYEE_PASSWORD`,`EMPLOYEE_MOBILE`,`EMPLOYEE_HOMEPHONE`) VALUES ('0', 'Bill', 'Riley', 'Bill_not_Bob', 'Bill72','0400323454','54824905');
INSERT INTO `Employee` (`EMPLOYEE_ID`,`EMPLOYEE_FIRST_NAME`,`EMPLOYEE_LAST_NAME`,`EMPLOYEE_USERNAME`,`EMPLOYEE_PASSWORD`,`EMPLOYEE_MOBILE`,`EMPLOYEE_HOMEPHONE`) VALUES ('1', 'Daniel', 'Mckelly', 'Dan86', 'McDan1986','0402343454','54426635');

/*Website Administrators*/
INSERT INTO `Website Administrators` (`EMPLOYEE_ID`) VALUES ('0');

/*Recipent*/
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('0','Mike','Thompson');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('1','Burger','Meister');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('2','John','Qsac');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('3','Ron','Burgendy');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('4','Matt','Daemon');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('5','Ivanna','Meister');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('6','Taylor','Swoft');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('7','Amy','Shumer');
INSERT INTO `Recipent`(`RECIPENT_ID`,`RECIPENT_FIRST_NAME`,`RECIPENT_LAST_NAME`) VALUES ('8','Amy','Poehler');

/*Addresses*/
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('0','52 Jack St','','4000','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('1','12 First St','','4001','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('2','9 Second St','','4000','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('3','603 Queens St','','4001','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('4','42 Albert St','','4178','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('5','805 Tank St','','4008','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('6','32 Ann St','','4106','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('7','52 Jack St','','4001','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('8','12 First St','','4178','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('9','9 Second St','','4106','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('10','3 Queens St','','4178','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('11','67 Albert St','','4106','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('12','75 Elizabeth St','','4008','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('13','25 William St','','4106','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('14','98 Margaret St','','4008','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('15','523 Felix St','','4106','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('16','34 Vulture St','','4178','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('17','32 Stanley St','','4106','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('18','52 Wellington St','','4008','Brisbane','QLD','Australia');
INSERT INTO `Addresses` (`ADDRESS_ID`,`ADDRESS_FIRST_LINE`,`ADDRESS_SECOND_LINE`,`ADDRESS_POSTCODE`,`ADDRESS_SUBURB`,`ADDRESS_STATE`,`ADDRESS_COUNTRY`) VALUES ('19','32 Gladstone St','','4106','Brisbane','QLD','Australia');


/*Orders*/
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('0','0','2','1','1','1','2015-11-11','2015-11-13','40.00','1','small box','DROPPED OFF','0','8');
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('1','1','4','1','1','1','2015-11-11','2015-11-13','24.00','2','vase','DROPPED OFF','1','9');
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('2','2','5','2','0','0','2015-11-11','2015-11-13','11.00','3','basketball','DROPPED OFF','2','10');
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('3','3','6','3','1','1','2015-11-11','2015-11-13','12.13','4','rare jems','DROPPED OFF','3','11');
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('4','4','4','4','0','1','2015-11-11','2015-11-14','77.12','5','mooses head','DROPPED OFF','4','12');
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('5', '5', '2','2','0','0','2015-11-13','2015-11-15','60.32','6','car tire','DROPPED OFF','5','13');
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('6', '5', '1','2','1','1','2015-11-15','2015-11-17','100.00','7','strange meat','DROPPED OFF','6','14');
INSERT INTO `Orders` (`RECIPENT_ID`,`ORDER_ID`,`SIZE`,`WEIGHT`,`ORDER_PICKED_UP_BY`,`ORDER_DROPPED_OFF_BY`,`DATE_OF_ORDER`,`DATE_OF_PICKUP`,`DATE_OF_DELIVERY`,`COST`,`CUSTOMER_ID`,`DESCRIPTION`,`STATUS_DESCRIPTION`,`PICKUP_LOCATION`,`DROP_OFF_LOCATION`) VALUES ('7', '5', '0.5','5','1','0','2015-11-15','2015-11-18','10.50','2','even stranger meat','DROPPED OFF','7','15');


/*no new lines because I'm a savage*/